// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs2tHPqxmHJ2v8Fvzir-t_vea1QlFdBIk',
    appId: '1:860906853096:android:042d3cbe91c290ee9eaf5d',
    messagingSenderId: '860906853096',
    projectId: 'advmobprog-firebase-7a32b',
    storageBucket: 'advmobprog-firebase-7a32b.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnL27L-VhMHXY359jHJt5mvDg4LWkyi5I',
    appId: '1:860906853096:web:e19dfb3455d0a47c9eaf5d',
    messagingSenderId: '860906853096',
    projectId: 'advmobprog-firebase-7a32b',
    authDomain: 'advmobprog-firebase-7a32b.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-7a32b.firebasestorage.app',
    measurementId: 'G-ZNN4FWFBT4',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMa61XZ9EJGpwO7j1rKAwTJw_LHr9JyBU',
    appId: '1:860906853096:ios:c12531c852af71a59eaf5d',
    messagingSenderId: '860906853096',
    projectId: 'advmobprog-firebase-7a32b',
    storageBucket: 'advmobprog-firebase-7a32b.firebasestorage.app',
    iosBundleId: 'com.example.chavezAdvmobprog2627',
  );
}
